# Site settings
locale        : "ko-KR"
title         : "Juyeons Page-portfolio blog"
description   : "This is a github portfolio & blog page published by Juyeon-Lee."
url           : "https://Juyeon-Lee.github.io" # the base hostname & protocol for your site
baseurl       : "/" # the subpath of your site, e.g. /blog/
bgurl         : "/blog/"
pfurl         : "/portfolio/"  # the subpath of your portfolio
repository    : "Juyeon-Lee/Juyeon-Lee.github.io"
breadcrumbs            : true # 브래드크럼 사용 여부 true, false (default) , _data/ui-text.yml에 다국어 지원 가능합니다.
words_per_minute       : 200 # 해당 포스트 읽는데 걸리는 시간을 계산하기 위해 대락 분당 읽는 수가 몇글자가 될지 적는 공간.


# User setting
owner: "Juyeon-Lee"
email: "ljo0831@naver.com"
facebook_username: "ljo0831"
twitter_username:
github_username: "Juyeon-Lee"
address: "Geumcheon-gu Seoul, South Korea"
  # Feel free to add more lines here 
telephone: "+082) 10-6600-3571"

# Defaults Post들에 적용될 기본 설정들
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
      author_profile: true

# Build settings
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:categories/:title/
paginate: 5 # 첫 페이지에보여줄 최근 게시물 수를 지정
paginate_path: /page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Gems
gems: [jekyll-paginate]
plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag