# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
author: Juyeon-Lee # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Juyeon-Lee # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/JuyeonLee97
    - https://www.linkedin.com/in/juyeon-lee-669753177
    - https://github.com/Juyeon-Lee
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Seoul # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Juyeon Lee's log" # The post list page content
    feature_text: |
      "파이썬, 자바 웹 백엔드 개발자가 되기 위해 노력중! 기록하고 싶은 것들 기록합니다."
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: ko # Set the site language
title: "Juyeons Page-portfolio blog" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/img/logo.png" # Site logo, also used in jekyll-seo-tag
description   : "This is a github portfolio & blog page published by Juyeon-Lee."
url           : "https://Juyeon-Lee.github.io"  # Site url, also used in jekyll-seo-tag
baseurl: "/"
repo: "https://github.com/Juyeon-Lee/Juyeon-Lee.github.io"
email: "ljo0831@naver.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  180: '/assets/logos/logo@180px.png'
  192: '/assets/logos/logo@192px.png'
  512: '/assets/logos/logo@512px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Portfolio
  url: /elements/
- title: Blog
  url: /blog/
- title: About
  url: /about/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Created by Juyeon-Lee
  url: https://github.com/Juyeon-Lee

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  FaceBook: https://www.facebook.com/JuyeonLee97
  LinkedIn: https://www.linkedin.com/in/juyeon-lee-669753177
  GitHub: https://github.com/Juyeon-Lee
  Telephone: "+082) 10-6600-3571"
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Build settings
markdown: kramdown
highlighter: rouge